# version: '3.8'
# services:
#   mongodb:
#     image: mongo:latest # use the latest image.
#     container_name: mongodb
#     ports:
#       - 27018:27017
#     volumes: # optional to preserve database after container is deleted.
#       - ./database-data:/data/db


version: "3.9"
services:
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --api-key ${STRIPE_API_KEY}  --forward-to host.docker.internal:8080/OnlineCourse/Webhook"
    env_file:
      - .env
    ports:
      - "8000:8000"
